
github: 	 angeletakis
patreon: 	 # Replace with a single patren username
open_collective: # Replace with a single Open Collective username
ko_fi: 		 angeletakis
tidelift: 	 # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom:		 # Replace with custom url (i.e. paypal, your website)
